using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shop_Editor
{
    public class P5Items
    {
        public static string[] ItemLists(ushort itemId)
        {
            if (itemId < 0x1000)
            {
                string[] MeleeWeaponArray =
                {
                    "Blank",
                    "Generic Gear",
                    "Rebel Knife",
                    "Kukri",
                    "Arsene's Cane",
                    "Blizz Dagger",
                    "Athame",
                    "Steel Kukri",
                    "Skinning Knife",
                    "Corvo",
                    "Kopis",
                    "Killing Scalpel",
                    "Mummy's Kopis",
                    "Quality Kopis",
                    "Pro Skinning Knife",
                    "Blood Corvo",
                    "Dirk",
                    "Parrying Dagger",
                    "Old Dirk",
                    "Machete",
                    "Baselard",
                    "Dual Edge Machete",
                    "Frenzy Dagger",
                    "Pro Parrying Dagger",
                    "Coma Dagger",
                    "Misericorde",
                    "Reserve",
                    "Pro Yamanaji",
                    "Amnesia",
                    "Reserve",
                    "Igniter",
                    "Ritual Athame",
                    "Shock Knife",
                    "Dancing Knife",
                    "Melancholia",
                    "Paradise Lost",
                    "Yamanaji",
                    "Normal Rod",
                    "Mace",
                    "Hell Slugger",
                    "Heavy Steel Pipe",
                    "Steel Pipe",
                    "Battle Hammer",
                    "Iron Pipe",
                    "Quality Steel Pipe",
                    "Heavy Mace",
                    "Spike Rod",
                    "Demon War Hammer",
                    "Bush Hammer",
                    "Demon Pipe",
                    "Megaton Rod",
                    "Boss Bush Hammer",
                    "Gaea Presser",
                    "Lotus Wand",
                    "Big Sleep Stick",
                    "Stun Baton",
                    "Death Crowbar",
                    "Dragon God Pole",
                    "Grand Presser",
                    "Stun Baton",
                    "Super Megido Rod",
                    "The Anchor",
                    "Erasure Hammer",
                    "Genocide Crowbar",
                    "Triple Crown Bat",
                    "Ruyi Jingu Bang",
                    "Wolf Fang Pole",
                    "Sleep Stick",
                    "Super Steel Whip",
                    "Flint Rod",
                    "Reserve",
                    "The Pulverizer",
                    "Mjolnir",
                    "Bandit Sword",
                    "Headhunter Ladle",
                    "Ryozanpaku Sword",
                    "Sonic Blade",
                    "Scimitar",
                    "Talwar",
                    "Bright Saber",
                    "Sleeper Blade",
                    "Shamshir",
                    "Blood Scimitar",
                    "Resting Sword",
                    "Chief's Cutlass",
                    "Quiet Sword",
                    "Cosmic Sword",
                    "Damascus Sword",
                    "Solar Blade",
                    "Heavy Saber",
                    "Master Shamshir",
                    "Panic Sword",
                    "Fury Blade",
                    "Bright Sword",
                    "Reserve",
                    "Answerer",
                    "Mega Flash Sword",
                    "Corona Blade",
                    "Claiomh Solais",
                    "Reserve",
                    "Machete",
                    "Plasma Sword",
                    "Kikouseiken",
                    "Vile Sword",
                    "El Caliente",
                    "God Saber",
                    "Heaven Saber",
                    "Deus Ex Machina",
                    "Leather Whip",
                    "Training Whip",
                    "Skin Ripper",
                    "Heat Whip",
                    "Warrior Whip",
                    "Blaze Whip",
                    "Burn Whip",
                    "Hero Whip",
                    "Tear Whip",
                    "Whip Sword",
                    "Electromag Whip",
                    "Disgrace Whip",
                    "Mirage Whip",
                    "Strike Tail",
                    "White Paper Whip",
                    "Great Whip Sword",
                    "Chain Whip",
                    "Barbed Wire",
                    "Pain and Pain",
                    "Spike Whip",
                    "Love Whip",
                    "Hard Branch",
                    "Coil Whip",
                    "Last Agony",
                    "Law Rope",
                    "Fundo-Kusari",
                    "Goat Leather Whip",
                    "Ingot Chain",
                    "Knout Whip",
                    "Death Knout",
                    "Cat-o-Nine Tails",
                    "Snow Queen's Whip",
                    "Death Match Wire",
                    "Naraka Whip",
                    "Katana",
                    "Gunto",
                    "Reserve",
                    "Imitation Katana",
                    "Unmarked Katana",
                    "Antique Gunto",
                    "Seishiki Sword",
                    "Muramasa",
                    "Jagato",
                    "Imperial Sword",
                    "Kirisame",
                    "Fury Blade",
                    "Iai Katana",
                    "Kunitsuna",
                    "Orochito",
                    "Wakizashi",
                    "Chidori",
                    "Masamune",
                    "Master's Iai Katana",
                    "Monohoshizao",
                    "Red Demon Blade",
                    "Quality Wakizashi",
                    "Reserve",
                    "Musou Masamune",
                    "Usumidori",
                    "Shimobashira",
                    "Shizukuto",
                    "Shikomi Kiseru",
                    "Kyokusui",
                    "Senryou Yakusha",
                    "Ame-no-Murakumo",
                    "Brass Knuckles",
                    "Hell Knuckles",
                    "Heavy Pound",
                    "Super Heavy Grip",
                    "Metal Duster",
                    "Hell Cestus",
                    "Iron Fist",
                    "Mach Punch",
                    "Bagh Naka",
                    "Demon Fist",
                    "Flash Punch",
                    "Fast Puncher",
                    "Omega Knuckle",
                    "Bout Gloves",
                    "Sanction",
                    "Dazzle Fist",
                    "One Inch",
                    "Chrome Duster",
                    "Grief Fist",
                    "Bear Gloves",
                    "Clenched Fist",
                    "Sabazios",
                    "Wrathful Iron Fist",
                    "Sealed Fist",
                    "Vajra",
                    "Reserve",
                    "Reserve",
                    "Reserve",
                    "Axe",
                    "Mega Axe",
                    "Steel Bardiche",
                    "Crescent Axe",
                    "Lethe Axe",
                    "Ice Axe",
                    "Melatonin Axe",
                    "Celtis",
                    "Lunatic Axe",
                    "Amazon Axe",
                    "Rend Celtis",
                    "Dragon Scale Axe",
                    "Perish Great Axe",
                    "Reserve",
                    "Reserve",
                    "Heracles Axe",
                    "Gilgamesh Axe",
                    "Narcolepsy",
                    "Fleurs du Mal",
                    "Reserve",
                    "Delta Knuckle",
                    "Heavy Grip",
                    "Lumina Saber",
                    "Reserve",
                    "Quasar Saber",
                    "Reserve",
                    "Falchion",
                    "Masquerade Ribbon",
                    "Reserve",
                    "Reserve",
                    "Haru Reserve 3",
                    "Haru Reserve 1",
                    "Bardiche",
                    "Death Contract",
                    "Black Kogatana",
                    "Reserve",
                    "Fault Knife",
                    "Quest Item",
                    "Lizard Tail Cutter",
                    "Envy Chain",
                    "Prophet's Hand",
                    "Dependence XX",
                    "Venture Saber",
                    "Slacker Pole",
                    "Silver Dagger",
                    "0x0F6",
                    "0x0F7",
                    "0x0F8",
                    "0x0F9",
                    "0x0FA",
                    "0x0FB",
                    "0x0FC",
                    "0x0FD",
                    "0x0FE",
                    "0x0FF",
                };
                return MeleeWeaponArray;
            }
            else if (itemId < 0x2000)
            {
                string[] ArmorArray =
                {
                    "Blank",
                    "Thief Clothes",
                    "Dark Undershirt",
                    "Print T-Shirt",
                    "Neckerchief",
                    "Baseball Jacket",
                    "Dress Shirt",
                    "Turtleneck",
                    "Pink Top",
                    "Loose Cutsew",
                    "Formal Shirt",
                    "0x00B",
                    "0x00C",
                    "Gold Breastplate",
                    "Grimy Gear",
                    "Soiled Armor",
                    "Shoulder Pads",
                    "Battle Camisole",
                    "Padded Shirt",
                    "Silk Scarf",
                    "Pauldrons",
                    "Old Camisole",
                    "Ancient Shirt",
                    "Well-worn Scarf",
                    "Burntech",
                    "Magic Camisole",
                    "Lynx Camo Vest",
                    "Cat Sweater",
                    "Old Blouse",
                    "Retro Camisole",
                    "Worn Chainmail",
                    "Guard Bandana",
                    "Survival Vest",
                    "Robust Apron",
                    "Chain Vest",
                    "Breeze Scarf",
                    "Okamoto Vest",
                    "Courbet Apron",
                    "Elegant Shirt",
                    "Flowing Scarf",
                    "Cosmic Undies",
                    "Lady's Dress",
                    "Austere Haori",
                    "E-Collar",
                    "Gaudy Undies",
                    "Scream Dress",
                    "Pollock Vest",
                    "Renoir Scarf",
                    "Acrylic-coated Gear",
                    "Paint-flecked Armor",
                    "0x032",
                    "0x033",
                    "Athletic Shirt",
                    "Power Camisole",
                    "Army Vest",
                    "Camo Collar",
                    "Nouveau Riche Shirt",
                    "Sponge Camisole",
                    "Gilded Vest",
                    "Fancy Collar",
                    "Saint's Tunic",
                    "Glaring Cape",
                    "Reckless Vest",
                    "Water Crown",
                    "Patron Undies",
                    "Accountant Cape",
                    "Bookkeeper Wrap",
                    "Flexible Collar",
                    "Tarnished Gear",
                    "Gold-tainted Armor",
                    "0x046",
                    "0x047",
                    "Plate Vest",
                    "Elysian Robe",
                    "Papal Robes",
                    "Id Collar",
                    "Vest of the Dead",
                    "Rosetta Corset",
                    "Pyramid Jacket",
                    "Bandage Collar",
                    "Retention Vest",
                    "Dogwatch Kimono",
                    "Hope Shirt",
                    "Sparkly Collar",
                    "Sand Gown",
                    "Pyramid Shawl",
                    "Royal Haori",
                    "Magical Scarf",
                    "Dust-crusted Gear",
                    "Timeworn Armor",
                    "0x05A",
                    "0x05B",
                    "Gigas Vest",
                    "Spiked Bra",
                    "Brigandine",
                    "Memorial Collar",
                    "UFO Vest",
                    "Astro Bra",
                    "Space Suit",
                    "Quiet Collar",
                    "Mythril Vest",
                    "Maillot",
                    "Dieting Wrap",
                    "Rubber Scarf",
                    "Moon Man Vest",
                    "Zero-G Undies",
                    "Akashic Shirt",
                    "Solar Wind Scarf",
                    "Spyware-laden Gear",
                    "Fragmented Armor",
                    "0x06E",
                    "0x06F",
                    "Fluted Guard",
                    "Rune Dress",
                    "Ghillie Vest",
                    "Measure Collar",
                    "Gambler Guard",
                    "Tsubofuri Wrap",
                    "Unyielding Vest",
                    "Scam Collar",
                    "Brave Waistcoat",
                    "Yama Dress",
                    "Egoist Shirt",
                    "Morose Collar",
                    "Lucky Waistcoat",
                    "Gambler Dress",
                    "Gambler Shirt",
                    "Gambler Collar",
                    "Seedy Gear",
                    "Smokestained Armor",
                    "0x082",
                    "0x083",
                    "Kaiser Vest",
                    "Kotodama Cape",
                    "Life Jacket",
                    "Killer Collar",
                    "Luxurious Vest",
                    "Aristocrat Cape",
                    "Magellan Robe",
                    "Revelry Collar",
                    "Fireman Happi",
                    "Mizuha Doumaru",
                    "Best Vest",
                    "Insomnia Collar",
                    "Captain's Vest",
                    "Millionaire Doumaru",
                    "Steel Chef Vest",
                    "Gorgeous Collar",
                    "Corrupt Gear",
                    "Classified Armor",
                    "0x096",
                    "0x097",
                    "Karna's Robe",
                    "Titanium Set",
                    "Silver Vest",
                    "Sublime Collar",
                    "Karna's Robe+",
                    "Titanium Set+",
                    "Silver Vest+",
                    "Sublime Collar+",
                    "Demon's Jacket",
                    "Haten Robe",
                    "Soul Vest",
                    "Nekomata Coat",
                    "Demon's Jacket+",
                    "Haten Robe+",
                    "Soul Vest+",
                    "Nekomata Coat+",
                    "Desecrated Gear",
                    "Unholy Armor",
                    "0x0AA",
                    "0x0AB",
                    "Over Guard",
                    "Diva Guard",
                    "Empathy Cape",
                    "Engetsu Collar",
                    "Over Guard+",
                    "Diva Guard+",
                    "Empathy Cape+",
                    "Engetsu Collar+",
                    "Immortal Vest",
                    "Sublime Bikini",
                    "Hero Jin-Baori",
                    "9 Lives Collar",
                    "Immortal Vest+",
                    "Sublime Bikini+",
                    "Hero Jinbaori+",
                    "9-Lives Collar+",
                    "Filth-caked Gear",
                    "Unsanitary Armor",
                    "RESERVE",
                    "RESERVE",
                    "Tantric Oath",
                    "Black Jacket",
                    "Official's Robe",
                    "Fusion Guard M 4",
                    "Silk Dress",
                    "Archangel Bra",
                    "Tapsuan",
                    "Fusion Guard F 4",
                    "King Frost Cape",
                    "Black Wing Robe",
                    "Fusion Guard 3",
                    "Fusion Guard 4",
                    "Frost Hood",
                    "Jack Hood",
                    "Black Robe",
                    "RESERVE",
                    "Empress Guard",
                    "Weird Wrap",
                    "Moonlight Robe",
                    "Lucifer Guard",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "0x100",
                    "0x101",
                    "0x102",
                    "0x103",
                    "0x104",
                    "0x105",
                    "0x106",
                    "0x107",
                    "0x108",
                    "0x109",
                    "0x10A",
                    "0x10B",
                    "0x10C",
                    "0x10D",
                    "0x10E",
                    "0x10F",
                    "0x110",
                    "0x111",
                    "0x112",
                    "0x113",
                    "0x114",
                    "0x115",
                    "0x116",
                    "0x117",
                    "0x118",
                    "0x119",
                    "0x11A",
                    "0x11B",
                    "0x11C",
                    "0x11D",
                    "0x11E",
                    "0x11F",
                    "0x120",
                    "0x121",
                    "0x122",
                    "0x123",
                    "0x124",
                    "0x125",
                    "0x126",
                    "0x127",
                    "0x128",
                    "0x129",
                    "0x12A",
                    "0x12B",
                    "0x12C",
                };
                return ArmorArray;
            }
            else if (itemId < 0x3000)
            {
                string[] AccessoryArray =
                {
                    "Blank",
                    "Hip Glasses ",
                    "Suspenders",
                    "Fanny Pack",
                    "Hairpin",
                    "Silver Key Ring",
                    "Black Tights",
                    "Dotted Tights",
                    "Headphones",
                    "Black Necktie",
                    "Worn Rosary",
                    "Breath Sash",
                    "Stamina Sash",
                    "Vitality Sash",
                    "Spirit Sash",
                    "Vigor Sash",
                    "Grit Sash",
                    "Chakra Choker",
                    "Mind Choker",
                    "Soul Choker",
                    "Aura Choker",
                    "Spirit Choker",
                    "Divine Choker",
                    "Red Band",
                    "Blue Band",
                    "Green Band",
                    "Yellow Band",
                    "Fire Bangle",
                    "Ice Bangle",
                    "Wind Bangle",
                    "Elec Bangle",
                    "Star Bracelet",
                    "Circular Band",
                    "White Band",
                    "Black Band",
                    "Nuclear Band",
                    "Kinetic Bangle",
                    "Holy Bangle",
                    "Grudge Bangle",
                    "Anger Bandana",
                    "Secret Hood",
                    "Stone Cap",
                    "Air Mino",
                    "Extra Mag 1",
                    "Extra Mag 2",
                    "Extra Mag 3",
                    "Wood Clappers",
                    "Hot Water Pouch",
                    "Rubber Gloves",
                    "Shield Goggles",
                    "Calming Mask",
                    "Wild Clogs",
                    "Notebook",
                    "Hunger Gem",
                    "Sleep Gem",
                    "Rage Gem",
                    "Despair Gem",
                    "Towser's Belt",
                    "Brain Guard",
                    "Burn Charm",
                    "Freeze Charm",
                    "Shock Charm",
                    "Dizzy Charm",
                    "Confuse Charm",
                    "Fear Charm",
                    "Forget Charm",
                    "Hunger Charm",
                    "Sleep Charm",
                    "Rage Charm",
                    "Despair Charm",
                    "Brainwash Charm",
                    "Zero-Day Pass",
                    "Revenge Mirror",
                    "Reprisal Mirror",
                    "Retribution Mirror",
                    "Power Anklet",
                    "Muscle Anklet",
                    "Soldier Anklet",
                    "Berserk Anklet",
                    "Hercules Anklet",
                    "Atlas Anklet",
                    "Magic Amulet",
                    "Witch Amulet",
                    "Druid Amulet",
                    "Rune Amulet",
                    "Wizard Amulet",
                    "Shaman Amulet",
                    "Strength Belt",
                    "Protect Belt",
                    "Fortress Belt",
                    "Armada Belt",
                    "Gigas Belt",
                    "Gaia Belt",
                    "Army Socks",
                    "Wing Socks",
                    "Purebred Socks",
                    "Cheetah Socks",
                    "Sonic Socks",
                    "Skanda Socks",
                    "Lucky Charm",
                    "Zodiac Charm",
                    "Feng Shui Charm",
                    "Bagua Charm",
                    "Guard Charm",
                    "Tyche Charm",
                    "Knight Crest",
                    "Hero Crest",
                    "Girard Medal",
                    "Olivier Medal",
                    "Roland Medal",
                    "Caesar Medal",
                    "Rakshasa Belt",
                    "Vajra Belt",
                    "Skanda Belt",
                    "Spirit Belt",
                    "Willful Belt",
                    "Hachiman Belt",
                    "Crimson Ring",
                    "Ignis Ring",
                    "Atar Ring",
                    "Ice Ring",
                    "Aurora Ring",
                    "Poli'ahu Ring",
                    "Elec Ring",
                    "Blitz Ring",
                    "Indra Ring",
                    "Wind Ring",
                    "Gale Ring",
                    "Kukulkan Ring",
                    "Atom Ring",
                    "Shelter Ring",
                    "Aegis Ring",
                    "Psychic Ring",
                    "Parapsy Ring",
                    "Akashic Ring",
                    "Shoten Ring",
                    "Heaven Ring",
                    "Nirvana Ring",
                    "Midnight Ring",
                    "Fallen Ring",
                    "Druj Ring",
                    "Resist Ring",
                    "Dispel Ring",
                    "Banish Ring",
                    "Bold Eyepatch",
                    "Hero Eyepatch",
                    "Epic Eyepatch",
                    "Fire Mask",
                    "Flame Cape",
                    "Blaze Cape",
                    "Ice Mask",
                    "Hail Cape",
                    "Blizzard Cape",
                    "Elec Mask",
                    "Thunder Cape",
                    "Blizzard Cape",
                    "Wind Mask",
                    "Gale Cape",
                    "Tempest Cape",
                    "Heat Mask",
                    "Heatwave Cape",
                    "Nuclear Cape",
                    "Psychic Mask",
                    "TK Cape",
                    "Abhijna Cape",
                    "Hamaya Mask",
                    "Royal Cape",
                    "Holy Cape",
                    "Protect Mask",
                    "Mystic Mask",
                    "Grudge Mask",
                    "Magic Rosary",
                    "Wizard Rosary",
                    "Makyou Rosary",
                    "Expedite Ring",
                    "Petra Genetrix",
                    "Khamrai Tao",
                    "Hua Khon",
                    "Daffodils",
                    "Legion's Jail",
                    "Thunder Band",
                    "Shackles",
                    "Vayu's Wrath",
                    "Regent",
                    "Queen's Necklace",
                    "Stone of Scone",
                    "Koh-i-Noor",
                    "Orlov",
                    "Emperor's Amulet",
                    "Hope Diamond",
                    "Crystal Skull",
                    "0x0BF",
                    "Miyuki's Earring",
                    "Harumi's Earring",
                    "Marronnier's Earring",
                    "Thief Mask",
                    "Black Rock",
                    "0x0C5",
                    "Vulcan Band",
                    "Neptune Band",
                    "Aquilo Band",
                    "Jupiter Band",
                    "Janus Band",
                    "Minerva Band",
                    "Venus Band",
                    "Pluto Band",
                    "Hades Harp",
                    "Menehune Dolls",
                    "Hawaiian Ring",
                    "Forneus Badge",
                    "Train Badge",
                    "PI Badge",
                    "Punch Badge",
                    "Betting Badge",
                    "Golf Badge",
                    "Tough Belt",
                    "Dandy Mirror",
                    "Leblanc Charm",
                    "Boss Undies",
                    "2nd Mate Badge",
                    "1st Mate Badge",
                    "Captain Badge",
                    "Regen Patch 1",
                    "Regen Patch 2",
                    "Regen Patch 3",
                    "SP Adhesive 1",
                    "SP Adhesive 2",
                    "SP Adhesive 3",
                    "Hot Compress",
                    "Grudge Gauze",
                    "Thought Gauze",
                    "Savage Band",
                    "Omnipotent Orb",
                    "Divine Pillar",
                    "Darkness Ring",
                    "White Headband",
                    "Attachment Pearl",
                    "Black Headband",
                    "Red Yarn Ball",
                    "Thunder Horns",
                    "Black Moon",
                    "Holy Stone",
                    "Team Glasses",
                    "SEES Armband",
                    "Sevens Emblem",
                    "Hermelin Badge",
                    "Arm PC",
                    "Midnight Bandana",
                    "Evoker",
                    "Honu Charm",
                    "Tiki Keychain",
                    "Beast Headphones",
                    "Babel Headphones",
                    "Lambs' Pillow",
                    "Gauntlet",
                    "Kuzunoha Tubes",
                };
                return AccessoryArray;
            }
            else if (itemId < 0x4000)
            {
                string[] ConsumableArray =
                {
                    "Blank",
                    "Devil Fruit",
                    "Recov-R: 50 mg",
                    "Recov-R: 100 mg",
                    "Takemedic",
                    "Life Stone",
                    "Bead",
                    "Takemedic-All",
                    "Takemedic-All V",
                    "Takemedic-All Z",
                    "Bead Chain",
                    "Soul Drop",
                    "Snuff Soul",
                    "Chewing Soul",
                    "Soul Food",
                    "Revival Bead",
                    "Balm of Life",
                    "RESERVE",
                    "Nohar-M",
                    "Relax Gel",
                    "Alert Capsule",
                    "RESERVE",
                    "RESERVE",
                    "Vanish Ball",
                    "Soma",
                    "Amrita Soda",
                    "Hiranya",
                    "Muscle Drink",
                    "Odd Morsel",
                    "Rancid Gravy",
                    "RESERVE",
                    "Magic Ointment",
                    "Physical Ointment",
                    "Rasetsu Ofuda",
                    "Idaten Ofuda",
                    "Kongou Ofuda",
                    "Kajaclear-R",
                    "Kundaclear-R",
                    "Molotov Cocktail",
                    "Blowtorch",
                    "Freeze Spray",
                    "Dry Ice",
                    "Air Cannon",
                    "Vacuum Cutter",
                    "Stun Gun",
                    "Tesla Coil",
                    "Megido Bomb",
                    "Sacramental Bread",
                    "Straw Doll",
                    "Hell Magatama",
                    "Cyclone Magatama",
                    "Frost Magatama",
                    "Arc Magatama",
                    "Psycho Bomb",
                    "Zener Cards",
                    "Atom Match",
                    "Kagutsuchi Orb",
                    "Happy Bomb",
                    "Segaki Rice",
                    "Curse Bomb",
                    "Five-inch Nail",
                    "Revivadrin",
                    "Medicine",
                    "Life Ointment",
                    "Homunculus",
                    "RESERVE",
                    "Reviv-All",
                    "Renew-All",
                    "Recover Oil",
                    "RESERVE",
                    "DVD Player",
                    "Garden Energy",
                    "Bio Nutrients",
                    "Mega Fertilizer",
                    "Psy Magatama",
                    "Nuclear Magatama",
                    "Bless Magatama",
                    "Curse Magatama",
                    "RESERVE",
                    "RESERVE",
                    "PC Tool Set",
                    "RESERVE",
                    "Glass Vase",
                    "Star Mirror",
                    "Snack Pack",
                    "Musty Pages",
                    "Homemaker Hero",
                    "Heart Ring",
                    "Heart Necklace",
                    "Designer Perfume",
                    "Incense Set",
                    "Mini Cactus",
                    "Flower Basket",
                    "Rose Bouquet",
                    "Black Mug",
                    "Sakura Fan",
                    "Fountain Pen",
                    "Robot Vacuum",
                    "Motorbike Figure",
                    "Local Mascot Set",
                    "Spotlight",
                    "Goho-M",
                    "RESERVE",
                    "Smokescreen",
                    "RESERVE",
                    "Hypno Mist",
                    "Stealthanol",
                    "Covertizer",
                    "RESERVE",
                    "Silk Yarn",
                    "Thick Parchment",
                    "Tin Clasp",
                    "Plant Balm",
                    "Cork Bark",
                    "Iron Sand",
                    "Condenser Lens",
                    "Aluminum Sheet",
                    "Tanned Leather",
                    "Red Phosphorus",
                    "Liquid Mercury",
                    "RESERVE",
                    "Wise Men's Words",
                    "Ghost Encounters",
                    "Tidying the Heart",
                    "Buchiko's Story",
                    "Scarlet Lipstick",
                    "RESERVE",
                    "Punch Ouch",
                    "Starvicks",
                    "Udagawa Water",
                    "CRT Television",
                    "RESERVE",
                    "Teen's Life",
                    "Master Swordsman",
                    "Flowerpedia",
                    "New Choju-Giga",
                    "PT Bible",
                    "Phan-Sightings",
                    "Annals of Greatness",
                    "Call Me Chief",
                    "How to Karakuri",
                    "Reckless Casanova",
                    "RESERVE",
                    "Junk",
                    "Money Distributor",
                    "Item Distributor",
                    "RESERVE",
                    "Jagariko",
                    "Broken Rock Salt",
                    "Movie Ticket",
                    "Movie 02 Ticket",
                    "Movie 03 Ticket",
                    "Movie 04 Ticket",
                    "RESERVE",
                    "RESERVE",
                    "Summer Lotto S",
                    "Autumn Bread",
                    "Element Set",
                    "Forces Set",
                    "Shitamachi Reborn",
                    "Star Forneus",
                    "Weekend Parks",
                    "Train of Life",
                    "Power Intuition",
                    "Bonehead",
                    "Crime Lab Squad",
                    "Not-so-hot Betsy",
                    "Bubbly Hills, 90210",
                    "ICU",
                    "RESERVE",
                    "Drizzled Natto",
                    "Squid Splurge",
                    "Idol Pins",
                    "Cheongsam",
                    "Gee Shock",
                    "RESERVE",
                    "Tokyo Shrines",
                    "Fishpond Spotter",
                    "Yoncha Wanderer",
                    "Museum of Stars",
                    "Jack Frost Doll",
                    "Burger-kun Doll",
                    "Wanna-kun Doll",
                    "Lexy Doll",
                    "Uji Matcha Flan",
                    "Chocolate Truffles",
                    "Potted Succulents",
                    "Limelight",
                    "Amateur Coffee",
                    "Harsh Coffee",
                    "Baptismal Water",
                    "Exorcism Water",
                    "Sacramental Wine",
                    "Repentance Ashes",
                    "Moist Katsu Bun",
                    "Book Cover",
                    "Castella",
                    "Crimson Lipstick",
                    "RESERVE",
                    "RESERVE",
                    "Tetra Hammer",
                    "Makara Hammer",
                    "Macadamia Choco",
                    "Macadamia Nuts",
                    "Hawaiian Cookie",
                    "Taiyaki Caramel",
                    "Yakisoba Candy",
                    "Jewel Shard",
                    "RESERVE",
                    "RESERVE",
                    "Casual Rod",
                    "Powerful Rod",
                    "Miracle Rod",
                    "Arginade",
                    "Dr. Salt NEO",
                    "Joylent",
                    "MRE Ration",
                    "Oatmeal Ration",
                    "Torimeshi Ration",
                    "Fruit Ration",
                    "Seafood Aojiru",
                    "Beauty Aojiru",
                    "Vitality Aojiru",
                    "Nasty Aojiru",
                    "Onsen Aojiru",
                    "RESERVE",
                    "Fulfiller",
                    "Summer Lotto R",
                    "Happy Pop",
                    "Thaw Stone",
                    "Extinguish Orb",
                    "Discharge Crystal",
                    "Second Maid",
                    "RESERVE",
                    "Sandwich",
                    "Fruit Danish",
                    "Chewy Anpan",
                    "Yakisoba Pan",
                    "Creature",
                    "Earl Green",
                    "Mad Bull",
                    "Muscle Tea",
                    "Manta",
                    "Nastea",
                    "1UP",
                    "Gambla Goemon",
                    "Golfer Sarutahiko",
                    "Calling Postcard",
                    "Refresh Aroma",
                    "Protein",
                    "Moist Protein",
                    "Fried Bread",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Beginner",
                    "Intermediate",
                    "Advanced",
                    "Hot Coffee",
                    "Nostalgic Steak",
                    "Frui-Tea",
                    "Totem Pole",
                    "Relaxing Coffee",
                    "Oo-hot Tea",
                    "Love★Pancake",
                    "Sincere Omelette",
                    "Makoto's Present",
                    "Haru's Present",
                    "Ann's Present",
                    "Futaba's Present",
                    "Sadayo's Present",
                    "Takemi's Present",
                    "Chihaya's Present",
                    "Ohya's Present",
                    "Hifumi's Present",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Small Boilie",
                    "Medium Boilie",
                    "Large Boilie",
                    "Top-class Boilie",
                    "Guardian Boilie",
                    "Big Bang Burger",
                    "Saturn Fries",
                    "Earth Burger",
                    "RESERVE",
                    "Moon Burger",
                    "Supernova Burger",
                    "Karaage King",
                    "Spring Fruit Pack",
                    "Foreign Nikuman",
                    "Phantom Wafers",
                    "Soothing Soba",
                    "Agodashi Oden",
                    "Party in a Can",
                    "Digital Camera",
                    "Face Beautifier",
                    "Laptop",
                    "RESERVE",
                    "Mini Dominion",
                    "Die-soujou",
                    "Decked Decarabia",
                    "Gear Girimehkala",
                    "Kinky Kin-Ki",
                    "Mossy Mothman",
                    "Movie 16 Ticket",
                    "Lockpick",
                    "Eternal Lockpick",
                    "Reserve Ammo",
                    "RESERVE",
                    "Treasure Trap",
                    "RESERVE",
                    "Red Fish",
                    "Rough Carp",
                    "Tokyo Bitterling",
                    "Seven-color Trout",
                    "White Carp",
                    "Treasure Trout",
                    "Delish Bitterling",
                    "Peerless Carp",
                    "Ichigaya Guardian",
                    "Adhesive Bandage",
                    "RESERVE",
                    "Rejuvenating IV",
                    "Leblanc Coffee",
                    "Soul Coffee",
                    "Awakening Coffee",
                    "Master Coffee",
                    "Decent Curry",
                    "Leblanc Curry",
                    "Master Curry",
                    "RESERVE",
                    "Shooting Card",
                    "Healing IV",
                    "Railroad Card",
                    "Fighting Card",
                    "RESERVE",
                    "Boxing Card",
                    "Gambling Card",
                    "Golf Card",
                    "The Okumura Way",
                    "Med. Tech for Teens",
                    "Guns of the World",
                    "Shogi World",
                    "Batting Science",
                    "Essence of Fishing",
                    "Speed Reading",
                    "Cinema Treasures",
                    "Pure Politics",
                    "Chinese Sweets",
                    "Theme Park Escort",
                    "The Great Thief",
                    "Pirate Legend",
                    "Zorro, the Outlaw",
                    "The Alluring Dancer",
                    "The Gallant Rogue",
                    "The Illusory Popess",
                    "Cry of Cthulhu",
                    "Woman in the Dark",
                    "The Hero with a Bow",
                    "Medjed Menace",
                    "Playing the Game",
                    "Game Secrets",
                    "Lotto Random",
                    "Lotto Series",
                    "Lotto Scratchcard",
                    "Rakugo Collection",
                    "Classical Hits",
                    "Best of KGB49",
                    "Wraith",
                    "Jail Break",
                    "Guy McVer",
                    "The Running Dead",
                    "The X Folders",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Vague",
                    "Nightlife Hotspots",
                    "Coolifier Pad",
                    "Hand Warmalizer",
                    "Venus Salad",
                    "Sikkenine",
                    "Sikkenine A",
                    "Sikkenine EX",
                    "Wide Eye Drops",
                    "Donut-Worry",
                    "Mental Floss",
                    "Hot and Sour Tea",
                    "Balloons",
                    "Kommissbrot",
                    "Beef Patty Ration",
                    "D Ration",
                    "Veg. Stew Ration",
                    "RESERVE",
                    "RESERVE",
                    "Durian-au-Lait",
                    "Oh! Shiruko",
                    "Chunky Potage",
                    "Ultimate Amazake",
                    "Udagawa Soda",
                    "Water of Rebirth",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Strawberry Curry",
                    "Mayo Locust",
                    "Miso Starfish",
                    "Mystery Stew",
                    "Bitter Coffee",
                    "Acidic Coffee",
                    "Fire Curry",
                    "Blaze Curry",
                    "Inferno Curry",
                    "Ramen Bowl",
                    "Night Pennant",
                    "Nude Statue",
                    "Swan Boat",
                    "Sky Tower Lamp",
                    "Giant Spatula",
                    "Idol Poster",
                    "Star Stickers",
                    "King Piece",
                    "Hero Figure",
                    "Hamaya",
                    "I <3 Tokyo Shirt",
                    "Non-Static Gum",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Sadayo's Chocolate",
                    "Takemi's Chocolate",
                    "Chihaya's Chocolate",
                    "Ohya's Chocolate",
                    "Hifumi's Chocolate",
                    "Makoto's Chocolate",
                    "Haru's Chocolate",
                    "Ann's Chocolate",
                    "Futaba's Chocolate",
                    "Ryuji's Chocolate",
                    "Sojiro's Chocolate",
                    "Kumade",
                    "Shumai Cushion",
                    "Gi-Nyant Doll",
                    "Sushi Mug",
                    "Choco Fountain",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Famidrive",
                    "RESERVE",
                    "Sheep Man Doll",
                    "Jam Bread",
                    "Melon Pan",
                    "Angel Tart",
                    "Moon Dango",
                    "Mixed Nuts",
                    "Beni-Azuma",
                    "Legendary Yaki-Imo",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Moonlight Carrot",
                    "Sun Tomato",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Ann Cream Puffs",
                    "Makoto Donuts",
                    "Sakura Amezaiku",
                    "Sadayo Taiyaki",
                    "Ryuji Dog",
                    "Amateur Curry",
                    "RESERVE",
                    "Broken Laptop",
                };
                return ConsumableArray;
            }
            else if (itemId < 0x5000)
            {
                string[] KeyItemArray =
                {
                    "BLANK",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Commuter Pass",
                    "Cigarettes",
                    "Key to Leblanc",
                    "Paper Bag",
                    "2nd Mate ID",
                    "1st Mate ID",
                    "Captain ID",
                    "Old Key",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Evil Snow Crystal",
                    "Sticky Hairball",
                    "Double Bookmark",
                    "RESERVE",
                    "Pen Case",
                    "Muffler",
                    "Cologne",
                    "Camera",
                    "Gloves",
                    "Wristwatch",
                    "Hat",
                    "Earmuffs",
                    "Headphones",
                    "RESERVE",
                    "Buchi Calculator",
                    "Dyed Handkerchief",
                    "Fashion Magazine",
                    "Promise List",
                    "Unlimited Service",
                    "Dog Tag",
                    "Fortune Tarot Card",
                    "Interview Notes",
                    "Kosha Piece",
                    "Sports Watch",
                    "Morgana's Scarf",
                    "Recipe Notes",
                    "Documentary Plans",
                    "Gecko Pin",
                    "Cell Key",
                    "Desire and Hope",
                    "Fountain Pen",
                    "Gun Controller",
                    "Business Card",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Castle Map",
                    "Tower Map",
                    "RESERVE",
                    "Kamoshida's Medal",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "The King Book",
                    "The Queen Book",
                    "The Slave Book",
                    "Green Key",
                    "Red Key",
                    "Randy Right Eye",
                    "Lustful Left Eye",
                    "Right Key",
                    "Left Key",
                    "Kaneshiro's Journal",
                    "Torn Page 1",
                    "Torn Page 2",
                    "Torn Page 3",
                    "Torn Page 4",
                    "Torn Page 5",
                    "Torn Page 6",
                    "Abyss Gem",
                    "Rejection Gem",
                    "Guilt Gem",
                    "Sanctuary Gem",
                    "Member's Card",
                    "Stolen Papyrus",
                    "Pyramid Sketch",
                    "Members Floor Map",
                    "High Limit Floor Map",
                    "Basement Blueprint",
                    "High Limit Card",
                    "Spaceport Map",
                    "Chief Clerk ID",
                    "Section Chief ID",
                    "Chief Director ID",
                    "Museum Brochure 1",
                    "Museum Brochure 2",
                    "Bank Blueprint",
                    "Bank Keycard",
                    "Casino Map",
                    "Security Keycard",
                    "Cruise Ship Map",
                    "Membership Card",
                    "VIP Invitation",
                    "Vermilion Disk",
                    "Vermilion Disk",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Escape Recipe",
                    "Mist Recipe",
                    "Home Recipe",
                    "Smoke Recipe",
                    "Energy Recipe",
                    "Sleep Recipe",
                    "Bronze Recipe",
                    "Scent Recipe",
                    "Silver Recipe",
                    "Smell Recipe",
                    "Gold Recipe",
                    "Aroma Recipe",
                    "Purify Recipe",
                    "Clone Recipe",
                    "Element Recipe",
                    "Life Recipe",
                    "Forces Recipe",
                    "Almighty Recipe",
                    "Vitality Recipe",
                    "Hyper Recipe",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                };
                return KeyItemArray;
            }
            else if (itemId < 0x6000)
            {
                string[] MaterialArray =
                {
                    "BLANK",
                    "Coward's Orb",
                    "Selfish Ornament",
                    "4th Girl's Talc",
                    "Notched Heart",
                    "Light Iron",
                    "Thick Hide",
                    "Glossy Clasp",
                    "Electric Rock",
                    "Magic Cross",
                    "Brave Lumber",
                    "Divine Bark",
                    "Thought Cross",
                    "Supple Metal",
                    "Smooth Fabric",
                    "Smart Clasp",
                    "Living Metal",
                    "Big Incisor",
                    "Glory Staff",
                    "Blessed Trumpet",
                    "Victor Laurel",
                    "Porcelain Teacup",
                    "Silver Cutlery",
                    "Strange Lantern",
                    "Nude Candle Stand",
                    "Shackles",
                    "Locked Collar",
                    "Dull Sword",
                    "Holey Helmet",
                    "Crushed Shield",
                    "Rusted Handcuffs",
                    "Chipped Glass",
                    "Ukiyo-e",
                    "Ink Wash Art",
                    "Hanging Scroll",
                    "Picture Scroll",
                    "Hannya Mask",
                    "Animal Brush",
                    "Fine Washi",
                    "Loose Sash",
                    "Cracked Vase",
                    "Sooty Kettle",
                    "Unsigned Mug",
                    "Plastic Frame",
                    "Crappy Portrait",
                    "Bad Sculpture",
                    "Gold Coin",
                    "Stock Certificate",
                    "Amber Stamp",
                    "Precious Bill",
                    "Rare Coin",
                    "Old Coin",
                    "Leather Case",
                    "Safe Dial",
                    "Money Counter",
                    "Office Calculator",
                    "Inkless Pen",
                    "Unopenable Lock",
                    "Worn Stamp",
                    "Tattered Wallet",
                    "Jewel Mummy",
                    "Gold Uraeus",
                    "Canopic Jar",
                    "Bastet Statue",
                    "Scarab Charm",
                    "Mummy Mask",
                    "Scratched Sword",
                    "Rusted Ankh",
                    "Torn Papyrus",
                    "Ra Mural",
                    "Sekhmet Mural",
                    "Sarcophagus Bit",
                    "Bent Staff",
                    "Pillar Piece",
                    "Moon Stone",
                    "Rare Metal",
                    "Sage Astrolabe",
                    "UFO Drone",
                    "Blade Flashlight",
                    "Rainbow Diode",
                    "Spaceship Stick",
                    "Robot Arm",
                    "Radar Antenna",
                    "Broken Telescope",
                    "Space Food",
                    "Punctured PCB",
                    "Dead Solar Panel",
                    "Warped Wheel",
                    "Luxury Watch",
                    "Gold Earrings",
                    "Damascene Cane",
                    "Silver Monocle",
                    "Ivory Dice",
                    "Dealer Ring",
                    "Magician Bowtie",
                    "Pro Dart",
                    "Card Shuffler",
                    "Dice Shaker",
                    "Gray Cufflinks",
                    "Faded Silk Hat",
                    "Smoked Cigar",
                    "Incomplete Deck",
                    "Coral Pendant",
                    "Pearl Necklace",
                    "Ebony Box",
                    "Marble Chessboard",
                    "Tortoise Hairpin",
                    "Cameo Brooch",
                    "Raden Plate",
                    "Peacock Fan",
                    "Bronze Compass",
                    "Brass Pocket Watch",
                    "Music Box",
                    "Old Kaleidoscope",
                    "Mirror Ball",
                    "Masquerade Mask",
                    "Pure Diamond",
                    "Dignity Ruby",
                    "Sublime Sapphire",
                    "Stable Emerald",
                    "Proper Turquoise",
                    "Brave Aquamarine",
                    "Harmony Amethyst",
                    "Intelligent Onyx",
                    "Wealth Pearl",
                    "Delight Opal",
                    "Charity Agate",
                    "Enduring Jade",
                    "Friendship Topaz",
                    "Truth Garnet",
                    "Grooved Gold",
                    "Hole Gold",
                    "Thin Gold",
                    "Grooved Silver",
                    "Hole Silver",
                    "Thin Silver",
                    "Grooved Copper",
                    "Hole Copper",
                    "Thin Copper",
                    "Onyx",
                    "Pearl",
                    "Amethyst",
                    "Turquoise",
                    "Opal",
                    "Topaz",
                    "Garnet",
                    "Aquamarine",
                    "Ruby",
                    "Emerald",
                    "Sapphire",
                    "Diamond",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "Old Milk Bottle",
                    "Bee Earrings",
                    "Scorpion Statue",
                    "Turtle Statue",
                    "Rotary Phone",
                    "Silk Bundle",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                    "RESERVE",
                };
                return MaterialArray;
            }
            else if (itemId < 0x7000)
            {
                string[] SkillCardArray =
                {
                    "BLANK (Unusable)",
                    "Agi",
                    "Agilao",
                    "Agidyne",
                    "Maragi",
                    "Maragion",
                    "Maragidyne",
                    "Bufu",
                    "Bufula",
                    "Bufudyne",
                    "Mabufu",
                    "Mabufula",
                    "Mabufudyne",
                    "Garu",
                    "Garula",
                    "Garudyne",
                    "Magaru",
                    "Magarula",
                    "Magarudyne",
                    "Zio",
                    "Zionga",
                    "Ziodyne",
                    "Mazio",
                    "Mazionga",
                    "Maziodyne",
                    "Hama",
                    "Hamaon",
                    "Mahama",
                    "Mahamaon",
                    "Kouha",
                    "Kouga",
                    "Kougaon",
                    "Makouha",
                    "Makouga",
                    "Makougaon",
                    "Mudo",
                    "Mudoon",
                    "Mamudo",
                    "Mamudoon",
                    "Eiha",
                    "Eiga",
                    "Eigaon",
                    "Maeiha",
                    "Maeiga",
                    "Maeigaon",
                    "Megido",
                    "Megidola",
                    "Megidolaon",
                    "Frei",
                    "Freila",
                    "Freidyne",
                    "Mafrei",
                    "Mafreila",
                    "Mafreidyne",
                    "Dazzler",
                    "Nocturnal Flash",
                    "Pulinpa",
                    "Tentarafoo",
                    "Evil Touch",
                    "Evil Smile",
                    "Makajama",
                    "Makajamaon",
                    "Famine's Breath",
                    "Famine's Scream",
                    "Dormina",
                    "Lullaby",
                    "Taunt",
                    "Wage War",
                    "Ominous Words",
                    "Abysmal Surge",
                    "Marin Karin",
                    "Brain Jack",
                    "Trapped Rat",
                    "Self-destruct",
                    "Self-destruct",
                    "Self-destruct",
                    "Life Drain",
                    "Spirit Drain",
                    "Life Leech",
                    "Spirit Leech",
                    "Foul Breath",
                    "Stagnant Air",
                    "Ghastly Wail",
                    "Inferno",
                    "Blazing Hell",
                    "Diamond Dust",
                    "Ice Age",
                    "Panta Rhei",
                    "Vacuum Wave",
                    "Thunder Reign",
                    "Wild Thunder",
                    "Divine Judgment",
                    "Samsara",
                    "Demonic Decree",
                    "Die For Me!",
                    "Atomic Flare",
                    "Cosmic Flare",
                    "Black Viper",
                    "Morning Star",
                    "Psi",
                    "Psio",
                    "Psiodyne",
                    "Mapsi",
                    "Mapsio",
                    "Mapsiodyne",
                    "Psycho Force",
                    "Psycho Blast",
                    "Lunge",
                    "Assault Dive",
                    "Megaton Raid",
                    "God's Hand",
                    "Lucky Punch",
                    "Miracle Punch",
                    "Cleave",
                    "Giant Slice",
                    "Brave Blade",
                    "Sword Dance",
                    "Hassou Tobi",
                    "Ayamur",
                    "Cornered Fang",
                    "Rising Slash",
                    "Deadly Fury",
                    "Snap",
                    "Triple Down",
                    "One-shot Kill",
                    "Riot Gun",
                    "Vajra Blast",
                    "Vorpal Blade",
                    "Vicious Strike",
                    "Heat Wave",
                    "Gigantomachia",
                    "Rampage",
                    "Swift Strike",
                    "Deathbound",
                    "Agneyastra",
                    "Double Fangs",
                    "Tempest Slash",
                    "Myriad Slashes",
                    "Sledgehammer",
                    "Skull Cracker",
                    "Terror Claw",
                    "Headbutt",
                    "Stomach Blow",
                    "Dream Needle",
                    "Hysterical Slap",
                    "Negative Pile",
                    "Brain Shake",
                    "Flash Bomb",
                    "Mind Slice",
                    "Bloodbath",
                    "Memory Blow",
                    "Insatiable Strike",
                    "Dormin Rush",
                    "Oni-Kagura",
                    "Bad Beat",
                    "Brain Buster",
                    "Dia",
                    "Diarama",
                    "Diarahan",
                    "Media",
                    "Mediarama",
                    "Mediarahan",
                    "Recarm",
                    "Samarecarm",
                    "Recarmdra",
                    "Amrita Drop",
                    "Amrita Shower",
                    "Mabaisudi",
                    "Salvation",
                    "Patra",
                    "Energy Shower",
                    "Energy Drop",
                    "Baisudi",
                    "Me Patra",
                    "Tarukaja",
                    "Rakukaja",
                    "Sukukaja",
                    "Heat Riser",
                    "Matarukaja",
                    "Marakukaja",
                    "Masukukaja",
                    "Thermopylae",
                    "Tarunda",
                    "Rakunda",
                    "Sukunda",
                    "Debilitate",
                    "Matarunda",
                    "Marakunda",
                    "Masukunda",
                    "Dekunda",
                    "Dekaja",
                    "Charge",
                    "Concentrate",
                    "Rebellion",
                    "Revolution",
                    "Tetrakarn",
                    "Makarakarn",
                    "Tetraja",
                    "Tetra Break",
                    "Makara Break",
                    "Fire Wall",
                    "Ice Wall",
                    "Elec Wall",
                    "Wind Wall",
                    "Fire Break",
                    "Ice Break",
                    "Wind Break",
                    "Elec Break",
                    "BLANK",
                    "BLANK",
                    "Nuke Wall",
                    "Psy Wall",
                    "Nuke Break",
                    "Psy Break",
                    "Counter",
                    "Counterstrike",
                    "High Counter",
                    "Endure",
                    "Enduring Soul",
                    "Dodge Bless",
                    "Dodge Curse",
                    "Survival Trick",
                    "Dodge Fire",
                    "Evade Fire",
                    "Dodge Ice",
                    "Evade Ice",
                    "Dodge Wind",
                    "Evade Wind",
                    "Dodge Elec",
                    "Evade Elec",
                    "Dodge Phys",
                    "Evade Phys",
                    "Fire Boost",
                    "Fire Amp",
                    "Ice Boost",
                    "Ice Amp",
                    "Wind Boost",
                    "Wind Amp",
                    "Elec Boost",
                    "Elec Amp",
                    "Angelic Grace",
                    "Divine Grace",
                    "Regenerate 1",
                    "Regenerate 2",
                    "Regenerate 3",
                    "Invigorate 1",
                    "Invigorate 2",
                    "Invigorate 3",
                    "Attack Master",
                    "Auto-Mataru",
                    "Defense Master",
                    "Auto-Maraku",
                    "Speed Master",
                    "Auto-Masuku",
                    "Fast Heal",
                    "Insta-Heal",
                    "Arms Master",
                    "Spell Master",
                    "Sharp Student",
                    "Apt Pupil",
                    "Ali Dance",
                    "Firm Stance",
                    "Life Aid",
                    "Victory Cry",
                    "Growth 1",
                    "Growth 2",
                    "Growth 3",
                    "Unshaken Will",
                    "Evade Bless",
                    "Evade Curse",
                    "BLANK",
                    "Resist Fire",
                    "Null Fire",
                    "Repel Fire",
                    "Drain Fire",
                    "Resist Ice",
                    "Null Ice",
                    "Repel Ice",
                    "Drain Ice",
                    "Resist Wind",
                    "Null Wind",
                    "Repel Wind",
                    "Drain Wind",
                    "Resist Elec",
                    "Null Elec",
                    "Repel Elec",
                    "Drain Elec",
                    "Resist Bless",
                    "Null Bless",
                    "Repel Bless",
                    "Drain Bless",
                    "Resist Curse",
                    "Null Curse",
                    "Repel Curse",
                    "Drain Curse",
                    "Resist Phys",
                    "Null Phys",
                    "Repel Phys",
                    "Drain Phys",
                    "Ailment Boost",
                    "Hama Boost",
                    "Mudo Boost",
                    "Dizzy Boost",
                    "Confuse Boost",
                    "Fear Boost",
                    "Forget Boost",
                    "Sleep Boost",
                    "Rage Boost",
                    "Despair Boost",
                    "BLANK",
                    "Brainwash Boost",
                    "Resist Dizzy",
                    "Resist Confuse",
                    "Resist Fear",
                    "Resist Forget",
                    "Resist Sleep",
                    "Resist Rage",
                    "Resist Despair",
                    "BLANK",
                    "Resist Brainwash",
                    "Null Dizzy",
                    "Null Confuse",
                    "Null Fear",
                    "Null Forget",
                    "Null Sleep",
                    "Null Rage",
                    "Null Despair",
                    "Null Brainwash",
                    "Burn Boost",
                    "Freeze Boost",
                    "Shock Boost",
                    "Fortified Moxy",
                    "Adverse Resolve",
                    "Last Stand",
                    "Heat Up",
                    "BLANK",
                    "Touch n' Go",
                    "Climate Decorum",
                    "Ambient Aid",
                    "Snipe",
                    "Cripple",
                    "Trigger Happy",
                    "Resist Nuke",
                    "Null Nuke",
                    "Repel Nuke",
                    "Drain Nuke",
                    "Resist Psy",
                    "Null Psy",
                    "Repel Psy",
                    "Drain Psy",
                    "Nuke Boost",
                    "Nuke Amp",
                    "Psy Boost",
                    "Psy Amp",
                    "Dodge Nuke",
                    "Evade Nuke",
                    "Dodge Psy",
                    "Evade Psy",
                    "Bless Boost",
                    "Bless Amp",
                    "Curse Boost",
                    "Curse Amp",
                    "Magic Ability",
                    "Fortify Spirit",
                    "Almighty Boost",
                    "Almighty Amp",
                    "Zenith Defense",
                    "Soul Chain",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "BLANK",
                    "Blank Card",
                };
                return SkillCardArray;
            }
            else if (itemId < 0x8000)
            {
                string[] OutfitArray =
                {
                    "Starter Clothes",
                    "Shujin Uniform",
                    "Phantom Suit",
                    "Pirate Armor",
                    "Morgana Classic",
                    "Red Latex Suit",
                    "Outlaw's Attire",
                    "Metal Rider",
                    "Musketeer Suit",
                    "Cyber Gear",
                    "Prince Suit",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Summer Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Winter Uniform",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Summer Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Winter Clothes",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Tracksuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Swimsuit",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Loungewear",
                    "Gekkoukan High",
                    "Gekkoukan High",
                    "Aigis Costume",
                    "Gekkoukan High",
                    "Gekkoukan High",
                    "Gekkoukan High",
                    "Gekkoukan High",
                    "Gekkoukan High",
                    "Gekkoukan High",
                    "Yasogami High",
                    "Yasogami High",
                    "Teddie Costume",
                    "Yasogami High",
                    "Yasogami High",
                    "Yasogami High",
                    "Yasogami High",
                    "Yasogami High",
                    "Yasogami High",
                    "St. Hermelin High",
                    "St. Hermelin High",
                    "Trish Costume v1",
                    "St. Hermelin High",
                    "St. Hermelin High",
                    "St. Hermelin High",
                    "St. Hermelin High",
                    "St. Hermelin High",
                    "St. Hermelin High",
                    "Seven Sisters High",
                    "Seven Sisters High",
                    "Trish Costume v2",
                    "Seven Sisters High",
                    "Seven Sisters High",
                    "Seven Sisters High",
                    "Seven Sisters High",
                    "Seven Sisters High",
                    "Kasugayama High",
                    "Vincent's Outfit",
                    "Orlando's Fashion",
                    "Stray Sheep Suit",
                    "Catherine's Cami",
                    "Johnny's Coat",
                    "Katherine's Outfit",
                    "Erica's Uniform",
                    "Toby's Overalls",
                    "Boss's Suit",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Karukozaka High",
                    "Hazama's Uniform",
                    "Butler Suit",
                    "Butler Suit",
                    "Maid Uniform",
                    "Maid Uniform",
                    "Butler Suit",
                    "Maid Uniform",
                    "Maid Uniform",
                    "Maid Uniform",
                    "Butler Suit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Christmas Outfit",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Dancewear",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Shadow Ops Uniform",
                    "Samurai Garb",
                    "Samurai Garb",
                    "Burroughs Costume",
                    "Samurai Garb",
                    "Samurai Garb",
                    "Samurai Garb",
                    "Samurai Garb",
                    "Samurai Garb",
                    "Samurai Garb",
                    "Student Uniform",
                    "Student Uniform",
                    "Gouto Costume",
                    "Ouran High",
                    "Student Uniform",
                    "Ouran High",
                    "Ouran High",
                    "Ouran High",
                    "Imperial Uniform",
                };
                return OutfitArray;
            }
            else if (itemId < 0x9000)
            {
                string[] RangedWeaponArray =
                {
                    "Blank",
                    "Handgun",
                    "Shotgun",
                    "Slingshot 1",
                    "Submachine Gun",
                    "Rifle 1",
                    "American Gun 1",
                    "Masaharu Gun 1",
                    "Aura Gun 1",
                    "Gun 009",
                    "Handgun",
                    "Gun 00B",
                    "Gun 00C",
                    "Rifle 2",
                    "Gun 014",
                    "Gun 015",
                    "Tkachev",
                    "Governance",
                    "Unmarked Pistol",
                    "Tkachev II",
                    "Tkachev HP",
                    "Makaronov",
                    "Makaronov II",
                    "Governance HP",
                    "Compact",
                    "Eliminator",
                    "Makaronov SP",
                    "Compact HP",
                    "Assassin",
                    "Assassin SP",
                    "Sand Hawk II",
                    "Model Gun",
                    "Levinson M31",
                    "Levinson M31 II",
                    "Granelli M3",
                    "Levinson M31 HP",
                    "Granelli M3 SP",
                    "Heavy Shotgun",
                    "Mad Maximum",
                    "Fireworks",
                    "Mad Maximum II",
                    "Heavy Shotgun II",
                    "Fireworks SP",
                    "Storm Shot",
                    "Pumpkin Bomb",
                    "Big Sleep",
                    "Masterkey",
                    "Orso Nero",
                    "Big Sleep SP",
                    "Storm Shot II",
                    "Fury SP",
                    "Bianchi SBAS II",
                    "Calamity Gun",
                    "Orso Nero SP",
                    "Volley Cannon II",
                    "Smithereens",
                    "Calamity Gun SP",
                    "Kiraihou II",
                    "Smithereens II",
                    "Unmarked Shotgun",
                    "Bianchi SBAS",
                    "Nock Volley",
                    "Hellfire",
                    "Nock Volley SP",
                    "Slingshot",
                    "Unmarked Sling",
                    "Slingshot SP",
                    "Slingshot HP",
                    "Shrike",
                    "Upsilon",
                    "Slingbow II",
                    "Comet 3",
                    "Shrike SP",
                    "Comet 3 II",
                    "Spirit Sling",
                    "Upsilon II",
                    "Stronger",
                    "Northern Light SP",
                    "Intercept",
                    "Stronger SP",
                    "Spirit Sling HP",
                    "Pirate Killer",
                    "Mt. Liang SP",
                    "Dreamstone",
                    "Intercept II",
                    "Sling Cannon",
                    "Sling Cannon II",
                    "Pirate Killer SP",
                    "Utopia HP",
                    "Dreamstone II",
                    "Catnap",
                    "Mount Liang",
                    "Shrike II",
                    "Northern Light",
                    "Shooting Star",
                    "Star Slayer",
                    "Replica SMG",
                    "Tommy Gun",
                    "Unmarked SMG",
                    "Trooper",
                    "MP2 Prototype",
                    "Flare SMG",
                    "Blitz MG",
                    "Sterlidge II",
                    "Trooper SP",
                    "MP2 Prototype II",
                    "Civilian MP",
                    "Hyakka Ryouran",
                    "No Mercy",
                    "Civilian MP II",
                    "Western SMG",
                    "No Mercy II",
                    "Tarantula SP",
                    "MP Victoria",
                    "Antares",
                    "Hien Renhappou",
                    "Western SMG II",
                    "MP Victoria EP",
                    "Honoikazuchi",
                    "H. Renhappou HP",
                    "Phantom Killer II",
                    "Honoikazuchi SP",
                    "Sterlidge",
                    "Brain Shot",
                    "Tommy Gun II",
                    "Flare SMG II",
                    "Tarantula",
                    "Blitz MGSP",
                    "Replica AR",
                    "Black Assault",
                    "AR-M4",
                    "Heavy Assault",
                    "G1 Type",
                    "AR-M4 II",
                    "AR-M4 SP",
                    "Black Assault SP",
                    "Hero AR",
                    "Heavy Assault II",
                    "Blaze Assault",
                    "Annihilator",
                    "Tempest",
                    "AR-X",
                    "Hero AR II",
                    "Cruel Carbine",
                    "Blaze Assault SP",
                    "Annihilator II",
                    "Tempest II",
                    "Cruel Carbine II",
                    "Sharpshooter",
                    "Ryuraihou II",
                    "Sharpshooter II",
                    "Hizutsu HP",
                    "Kuzuryu Gouhou",
                    "G1 Type SP",
                    "Rebel Rifle",
                    "Rebel Rifle SP",
                    "Tempest HP",
                    "Hizutsu",
                    "Ryuraihou",
                    "Heaven's Gate",
                    "Replica Revolver",
                    "Peacemaker",
                    "P Revolver",
                    "PM Sheriff",
                    "PM Sheriff II",
                    "Ling Xing",
                    "P Revolver II",
                    "Peacemaker SP",
                    "Justness",
                    "Justness II",
                    "Evil Roulette",
                    "Wildborn SP",
                    "Artillery",
                    "Evil Roulette II",
                    "Ling Xing II",
                    "Calvary",
                    "Artillery II",
                    "Baptism SP",
                    "Orochi SP",
                    "Cavalry II",
                    "Twilight SP",
                    "Peacemaker HP",
                    "Mirrirmina",
                    "Wildborn",
                    "Baptism",
                    "Orochi",
                    "Twilight",
                    "Judge of the Dead",
                    "Fury",
                    "Volley Cannon",
                    "Kiraihou",
                    "Megido Fire",
                    "GL Replica",
                    "Pawzooka",
                    "Unmarked GL",
                    "GL Mega",
                    "GL Rep",
                    "Scorcher",
                    "GL Replica II",
                    "Multiple GL",
                    "Scorcher SP",
                    "Eraser",
                    "Town Burner HP",
                    "Flame Ocean",
                    "Eraser SP",
                    "Multiple GL II",
                    "Magma Bucket",
                    "Magma Bucket SP",
                    "Flame Ocean II",
                    "Pandemonium SP",
                    "Haru Reserve",
                    "Haru Reserve 2",
                    "Town Burner",
                    "Town Burner SP",
                    "Pandemonium",
                    "Yagrush",
                    "H. Ryouran HP",
                    "Antares II",
                    "Phantom Killer",
                    "Wild Hunt",
                    "Clemont Shot",
                    "Golden Beam",
                    "Gun 222",
                    "Gun 223",
                    "Moebius",
                    "Moebius II",
                    "Sirius",
                    "Sirius SP",
                    "Slingbow",
                    "Star Slayer HP",
                    "Utopia",
                    "Sudarshana",
                    "Sleeper",
                    "Karura II",
                    "From Heaven",
                    "Crimson Gun HP",
                    "Riot Police SP",
                    "Gravity Gun",
                    "Medusan",
                    "Sleeper SP",
                    "R.I.Pistol",
                    "Medusan II",
                    "R.I.Pistol II",
                    "Gravity Gun HP",
                    "Nataraja",
                    "Riot Police",
                    "Sand Hawk",
                    "Karura",
                    "Crimson Gun",
                    "From Heaven II",
                    "Cocytus",
                    "Cocytus SP",
                    "Tyrant Pistol",
                    "Gun 253",
                    "Gun 254",
                    "Gun 255",
                };
                return RangedWeaponArray;
            }
            else
            {
                string[] InvalidItem =
                {
                    "invalid Item"
                };
                return InvalidItem;
            }
        }
    }
}
